import { PERMISSIONS, type Permission } from './permissions.js';

export const ROLES = {
  SUPER_ADMIN:         'super_admin',
  HOSPITAL_ADMIN:      'hospital_admin',
  DOCTOR:              'doctor',
  NURSE:               'nurse',
  NURSE_PRACTITIONER:  'nurse_practitioner',
  PHYSICIAN_ASSISTANT: 'physician_assistant',
  LAB_TECH:            'lab_tech',
  PHARMACIST:          'pharmacist',
  RECEPTION:           'reception',
  TECH:                'tech',
} as const;

export type SystemRole = (typeof ROLES)[keyof typeof ROLES];

export const SYSTEM_ROLES: SystemRole[] = Object.values(ROLES) as SystemRole[];

// super_admin bypasses all permission checks — no permissions list needed.
// All other system roles have an explicit default permission set.
export const DEFAULT_ROLE_PERMISSIONS: Record<Exclude<SystemRole, 'super_admin'>, Permission[]> = {
  hospital_admin: [
    PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_INVITE, PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_SUSPEND,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_TRANSFER,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_MEDICATIONS_VIEW, PERMISSIONS.EMR_DOCUMENTS_WRITE,
    PERMISSIONS.EMR_ACCESS_LOG_VIEW, PERMISSIONS.EMR_BREAK_GLASS,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.ASSET_VIEW, PERMISSIONS.ASSET_CREATE, PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_STATUS, PERMISSIONS.ASSET_MOVE,
    PERMISSIONS.REVIEW_VIEW, PERMISSIONS.REVIEW_ACT,
    PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  doctor: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_TRANSFER,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_VITALS_RECORD,
    PERMISSIONS.EMR_MEDICATIONS_VIEW, PERMISSIONS.EMR_MEDICATIONS_WRITE,
    PERMISSIONS.EMR_HISTORY_WRITE, PERMISSIONS.EMR_PROCEDURES_WRITE,
    PERMISSIONS.EMR_IMMUNIZATIONS_WRITE, PERMISSIONS.EMR_DOCUMENTS_WRITE,
    PERMISSIONS.EMR_BREAK_GLASS,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_CREATE, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RELEASE,
    PERMISSIONS.REVIEW_VIEW, PERMISSIONS.REVIEW_ACT,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  nurse: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_ADMIT,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_VITALS_RECORD,
    PERMISSIONS.EMR_MEDICATIONS_VIEW,
    PERMISSIONS.EMR_HISTORY_WRITE, PERMISSIONS.EMR_PROCEDURES_WRITE,
    PERMISSIONS.EMR_IMMUNIZATIONS_WRITE,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_CREATE, PERMISSIONS.LAB_PROCESS,
    PERMISSIONS.REVIEW_VIEW,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  nurse_practitioner: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_TRANSFER,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_VITALS_RECORD,
    PERMISSIONS.EMR_MEDICATIONS_VIEW, PERMISSIONS.EMR_MEDICATIONS_WRITE,
    PERMISSIONS.EMR_HISTORY_WRITE, PERMISSIONS.EMR_PROCEDURES_WRITE,
    PERMISSIONS.EMR_IMMUNIZATIONS_WRITE, PERMISSIONS.EMR_DOCUMENTS_WRITE,
    PERMISSIONS.EMR_BREAK_GLASS,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_CREATE, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RELEASE,
    PERMISSIONS.REVIEW_VIEW, PERMISSIONS.REVIEW_ACT,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  physician_assistant: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_TRANSFER,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_VITALS_RECORD,
    PERMISSIONS.EMR_MEDICATIONS_VIEW, PERMISSIONS.EMR_MEDICATIONS_WRITE,
    PERMISSIONS.EMR_HISTORY_WRITE, PERMISSIONS.EMR_PROCEDURES_WRITE,
    PERMISSIONS.EMR_IMMUNIZATIONS_WRITE, PERMISSIONS.EMR_DOCUMENTS_WRITE,
    PERMISSIONS.EMR_BREAK_GLASS,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_CREATE, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RELEASE,
    PERMISSIONS.REVIEW_VIEW, PERMISSIONS.REVIEW_ACT,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  lab_tech: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_MEDICATIONS_VIEW,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_CREATE, PERMISSIONS.LAB_PROCESS,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  pharmacist: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.EMR_VIEW, PERMISSIONS.EMR_MEDICATIONS_VIEW,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  reception: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_TRANSFER,
    PERMISSIONS.SEARCH_USE, PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  tech: [
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.ASSET_VIEW, PERMISSIONS.ASSET_CREATE, PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_STATUS, PERMISSIONS.ASSET_MOVE, PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
};
