// Centralised icon proxy. The rest of the codebase imports from `@icons`
// (mapped in each app's tsconfig/vite alias) so we can swap the icon source
// in one place — currently lucide-react.
export {
  // Navigation & shell
  Home as IconHome,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  ChevronDown as IconChevronDown,
  ChevronUp as IconChevronUp,
  Menu as IconMenu,
  X as IconClose,
  LogOut as IconLogout,
  Settings as IconSettings,
  Search as IconSearch,
  Bell as IconBell,
  SlidersHorizontal as IconFilters,
  MoreHorizontal as IconMoreHorizontal,
  MoreVertical as IconMoreVertical,
  ArrowLeft as IconArrowLeft,
  ArrowRight as IconArrowRight,
  ExternalLink as IconExternalLink,
  Copy as IconCopy,
  Check as IconCheck,
  // People & staff
  User as IconUser,
  Users as IconUsers,
  UserPlus as IconUserPlus,
  UserCheck as IconUserCheck,
  UserX as IconUserX,
  Shield as IconShield,
  // Patients & clinical
  HeartPulse as IconHeartPulse,
  Activity as IconActivity,
  Stethoscope as IconStethoscope,
  Pill as IconPill,
  FlaskConical as IconFlask,
  Syringe as IconSyringe,
  Thermometer as IconThermometer,
  ClipboardList as IconClipboard,
  FileText as IconFileText,
  FilePlus as IconFilePlus,
  FileSearch as IconFileSearch,
  Microscope as IconMicroscope,
  // Hospital & workspace
  Building2 as IconBuilding,
  Layers as IconLayers,
  Network as IconNetwork,
  QrCode as IconQrCode,
  Barcode as IconBarcode,
  ScanLine as IconScan,
  // Status & feedback
  AlertTriangle as IconAlert,
  AlertCircle as IconAlertCircle,
  Info as IconInfo,
  CheckCircle as IconCheckCircle,
  XCircle as IconXCircle,
  Clock as IconClock,
  RefreshCw as IconRefresh,
  Loader2 as IconLoader,
  // Actions
  Plus as IconPlus,
  Trash2 as IconTrash,
  Edit2 as IconEdit,
  Upload as IconUpload,
  Download as IconDownload,
  Printer as IconPrint,
  Send as IconSend,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  Star as IconStar,
  Lock as IconLock,
  Unlock as IconUnlock,
  // Assets & location
  MapPin as IconMapPin,
  Package as IconPackage,
  Tag as IconTag,
  // Misc
  BarChart3 as IconChart,
  Map as IconMap,
  Calendar as IconCalendar,
  Link as IconLink,
  // Legacy aliases kept for existing usage
  ChevronLeft as IconBack,
  ChevronRight as IconForward,
} from 'lucide-react';
