export const ROUTES = {
  HOME: '/',
  TOKENS: '/tokens',
  BUTTONS: '/buttons',
  INPUTS: '/inputs',
  SELECTION: '/selection',
  DATETIME: '/datetime',
  SPECIALIZED: '/specialized',
  AVATARS_PILLS: '/avatars-pills',
  SKELETON_PROGRESS: '/skeleton-progress',
  TOOLTIP: '/tooltip',
  CARDS: '/cards',
  TABLES: '/tables',
  MODALS: '/modals',
  BANNERS: '/banners',
  NAVIGATION: '/navigation',
  FEEDBACK: '/feedback',
  LAB: '/lab',
  VITALS: '/vitals',
  CHARTS: '/charts',
  EMR: '/emr',
  BED_BOARD: '/bed-board',
  TELEHEALTH: '/telehealth',
  EQUIPMENT: '/equipment',
  STAFF: '/staff',
  REGISTRATION: '/registration',
} as const;

export type Route = (typeof ROUTES)[keyof typeof ROUTES];
